from qtest_library import *

qtest_list_dict = {}

qtest_list_dict["MECCDEqualizedImage"] = []
qtest_list_dict["MECCDMeanImage"] = []
qtest_list_dict["MECCDStdImage"] = []
qtest_list_dict["MEFitCalibrationPerCol"] = []
qtest_list_dict["MEFitCalibrationPerRow"] = []
qtest_list_dict["MEFitDC"] = []
qtest_list_dict["MEFitDCCalibration"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image, qtest_chi2FromFit]
qtest_list_dict["MEFitDCLambda"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_chi2FromFit, qtest_residuals_per_image,]
qtest_list_dict["MEFitDCMu0"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image, qtest_chi2FromFit]
qtest_list_dict["MEFitDCPerCol"] = []
qtest_list_dict["MEFitDCPerRow"] = []
qtest_list_dict["MEFitDCSigma"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image, qtest_chi2FromFit]
qtest_list_dict["MEFitMu0PerCol"] = []
qtest_list_dict["MEFitMu0PerRow"] = []
qtest_list_dict["MEFitSigmaPerCol"] = []
qtest_list_dict["MEFitSigmaPerRow"] = []
qtest_list_dict["MEInterceptFromMeanPCPerRow"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image]
qtest_list_dict["MEMADPixelChargePerCol"] = [qtest_tt, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEMADPixelChargePerRow"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEMeanPixelChargePerRow"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEMedianPixelChargePerCol"] = [qtest_tt, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEMedianPixelChargePerRow"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEOVSMADPixelChargePerRow"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEOVSMedianPixelChargePerRow"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEOVSPCD"] = []
qtest_list_dict["MEOVSPedestalMu"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image]
qtest_list_dict["MEOVSPedestalMuPerRow"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEOVSPedestalSigma"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_image]
qtest_list_dict["MEOVSPedestalSigmaPerRow"] = []#[qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MEPCD"] = []
qtest_list_dict["MEQmeanDiffSingleSkips"] = []
qtest_list_dict["MEReadoutnoiseNDCM"] = []
qtest_list_dict["MESTDPixelChargePerRow"] = [qtest_tt, qtest_chi2, qtest_ks, qtest_residuals_per_rowCol]
qtest_list_dict["MESlopeFromMeanPCPerRow"] = []
